In [1]:
import pandas as pd

In [26]:
def raw_to_clean_marital(Raw) :
    marital = pd.read_csv(Raw)
    clean_marital = marital[['B12001e1']].copy() #Total pop
    
    # Categories
    clean_marital['marriedP'] = marital[['B12001e5','B12001e14']].agg("sum", axis="columns") #married present
    clean_marital['marriedA'] = marital[['B12001e6','B12001e15']].agg("sum", axis="columns") #married absent
    clean_marital['NM'] = marital[['B12001e3','B12001e12']].agg("sum", axis="columns") #never married
    clean_marital['D'] = marital[['B12001e10','B12001e19']].agg("sum", axis="columns") #divorced
    clean_marital['W'] = marital[['B12001e9','B12001e18']].agg("sum", axis="columns") #widowed
    
#     # Female Categories
#     clean_marital['marriedPf'] = marital['B12001e14'] #married present
#     clean_marital['marriedAf'] = marital['B12001e15'] #married absent
#     clean_marital['NMf'] = marital['B12001e12'] #never married
#     clean_marital['Df'] = marital['B12001e19'] #divorced
#     clean_marital['Wf'] = marital['B12001e18'] #widowed
    
    # Find proportions for males
    clean_marital['Married Present'] = clean_marital.apply(lambda x: x['marriedP'] if x['marriedP'] < 1 else x['marriedP']/x['B12001e1'], axis=1)
    clean_marital['Married Absent'] = clean_marital.apply(lambda x: x['marriedA'] if x['marriedA'] < 1 else x['marriedA']/x['B12001e1'], axis=1)
    clean_marital['Never Married'] = clean_marital.apply(lambda x: x['NM'] if x['NM'] < 1 else x['NM']/x['B12001e1'], axis=1)
    clean_marital['Divorced'] = clean_marital.apply(lambda x: x['D'] if x['D'] < 1 else x['D']/x['B12001e1'], axis=1)
    clean_marital['Widowed'] = clean_marital.apply(lambda x: x['W'] if x['W'] < 1 else x['W']/x['B12001e1'], axis=1)
    
#     # Find proportions for females
#     clean_marital['Female: Married Present'] = clean_marital.apply(lambda x: x['marriedPf'] if x['marriedPf'] < 1 else x['marriedPf']/x['B12001e11'], axis=1)
#     clean_marital['Female: Married Absent'] = clean_marital.apply(lambda x: x['marriedAf'] if x['marriedAf'] < 1 else x['marriedAf']/x['B12001e11'], axis=1)
#     clean_marital['Female: Never Married'] = clean_marital.apply(lambda x: x['NMf'] if x['NMf'] < 1 else x['NMf']/x['B12001e11'], axis=1)
#     clean_marital['Female: Divorced'] = clean_marital.apply(lambda x: x['Df'] if x['Df'] < 1 else x['Df']/x['B12001e11'], axis=1)
#     clean_marital['Female: Widowed'] = clean_marital.apply(lambda x: x['Wf'] if x['Wf'] < 1 else x['Wf']/x['B12001e11'], axis=1)

    # Drop all unnecessary columns
    clean_marital = clean_marital.drop(['B12001e1'],axis=1)
    clean_marital = clean_marital.drop(['marriedP','marriedA','NM','D','W'],axis=1)
#     clean_marital = clean_marital.drop(['marriedPf','marriedAf','NMf','Df','Wf'],axis=1)
    
    # Add GEOID and ensure it is in the first column
    clean_marital['GEOID'] = marital['GEOID']
    cols = clean_marital.columns.tolist()
    cols.insert(0, cols.pop(cols.index('GEOID')))
    clean_marital = clean_marital.reindex(columns= cols)
    
    return clean_marital

In [27]:
new_clean = raw_to_clean_marital('train/X12_MARITAL_STATUS_AND_HISTORY.csv')
new_clean.to_csv('marital_status.csv')

In [28]:
new_clean.head()

,GEOID,Married Present,Married Absent,Never Married,Divorced,Widowed
0,15000US060014001001,0.605629,0.028143,0.226642,0.079174,0.060413
1,15000US060014002001,0.546256,0.028634,0.272026,0.112335,0.040749
2,15000US060014002002,0.406961,0.053548,0.394913,0.097724,0.046854
3,15000US060014003001,0.503435,0.122669,0.305201,0.047105,0.021590
4,15000US060014003002,0.260239,0.017065,0.555461,0.063993,0.103242